export const UPDATE_RESOURCE = "UPDATE_RESOURCE";
// Fetch list
export const REQUEST_RESOURCES = "REQUEST_RESOURCES";
export const REQUEST_RESOURCES_SUCCESS = "REQUEST_RESOURCES_SUCCESS";
export const REQUEST_RESOURCES_FAIL = "REQUEST_RESOURCES_FAIL";
// Create
export const REQUEST_CREATE_RESOURCE = "REQUEST_CREATE_RESOURCE";
export const REQUEST_CREATE_RESOURCE_SUCCESS = "REQUEST_CREATE_RESOURCE_SUCCESS";
export const REQUEST_CREATE_RESOURCE_FAIL = "REQUEST_CREATE_RESOURCE_FAIL";
// Update
export const REQUEST_UPDATE_RESOURCE = "REQUEST_UPDATE_RESOURCE";
export const REQUEST_UPDATE_RESOURCE_SUCCESS = "REQUEST_UPDATE_RESOURCE_SUCCESS";
export const REQUEST_UPDATE_RESOURCE_FAIL = "REQUEST_UPDATE_RESOURCE_FAIL";
// Remove
export const REQUEST_REMOVE_RESOURCE = "REQUEST_REMOVE_RESOURCE";
export const REQUEST_REMOVE_RESOURCE_SUCCESS = "REQUEST_REMOVE_RESOURCE_SUCCESS";
export const REQUEST_REMOVE_RESOURCE_FAIL = "REQUEST_REMOVE_RESOURCE_FAIL";
