export const ADD_RESOURCE = "ADD_RESOURCE";
export const REMOVE_RESOURCE = "REMOVE_RESOURCE";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";

export const FETCH_RESOURCES_REQUEST = "FETCH_RESOURCES_REQUEST";
export const FETCH_RESOURCES_SUCCESS = "FETCH_RESOURCES_SUCCESS";
export const FETCH_RESOURCES_FAILURE = "FETCH_RESOURCES_FAILURE"; 
